on: [push] # push ä»£ç æ—¶è§¦å‘
jobs: 
    deploy: 
        runs-on: ubuntu-latest
        name: Tencent Cloudbase Github Action Example
        steps: 
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
          run: |
            npm ci
            npm run build
          
        # ä½¿ç”¨äº‘å¼€å‘ Github Action éƒ¨ç½²
        - name: Tencent CloudBase Github Action
          uses: TencentCloudBase/cloudbase-action@v2.0.1
          with: 
            # äº‘å¼€å‘çš„è®¿é—®å¯†é’¥ secretId å’Œ secretKey
            secretId: ${{ secrets.secretId }}
            secretKey: ${{ secrets.secretKey }}
            # äº‘å¼€å‘çš„ç¯å¢ƒid
            envId: ${{ secrets.envId }}
            # Github é¡¹ç›®é™æ€æ–‡ä»¶çš„è·¯å¾„
            staticSrcPath: build
